{% set name = "bootstrap_contrast" %}
{% set version = "0.327" %}
{% set sha256 = "fd2ec9c2170c2b84ce49a0520c1b3527c6e4aa8fbec653f9c271ffb56be4790f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - seaborn
    - pandas
    - numpy
    - scipy

test:
  imports:
    - bootstrap_contrast

about:
  home: http://github.com/josesho/bootstrap_contrast
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Python module to produce bootstrapped confidence intervals and effect sizes.'
  description: 'Python module to produced bootstrapped confidence intervals and effect sizes. Requires matplotlib, seaborn, numpy, scipy, and pandas (version at least 0.20.3).'
  doc_url: https://github.com/josesho/bootstrap_contrast/blob/master/README.md
  dev_url: http://github.com/josesho/bootstrap_contrast

extra:
  recipe-maintainers:
    - josesho
