travis:
  secure:
    BINSTAR_TOKEN: yUDgybimy3MhDlOG8hVcNpLeZENhrP90M0obViIisxOH13/mfj5wBP0rhgOXDA5ARIztV13hjbCYkqQME2Q4iwKM7NAbh5tBxbqBUWtmEU3EJO04q5weNFBgB5zJRGK+ITir4TYwsfnnoX4xfL+WzQyBplnTA4uV4QU8HQNEQQwA32AufWPEnmbwJfMBtWuNH2Lcd8eG4VeTYMRQUm0c0whH1T5QBslJRZIZjZKbcdXzDg31qFBa0VNEMR9+Ot9WdJZj9E3tz6/uhMKzyvKHq2/NSzAdlLjJjB1CMy38A96cs41ypwjr45LTkGZRh8B5bCQYQWctX2CvUEU4cmY5DMUV3CmfojrBwsqCriqicaf+IfO3AqUOH0nXjmBIIcYpk/AT7aqtqeUAKzgYqeqBtzW/xmvZ81ZrXDNWryQ6zvETFrWcAVSW7QDptSGJLkblumwuZUIbqEEDTr+Nsv/YFoRPhwlNky+NrZD3sBZ5gOhE7Ojq34rZZnjvXQtiVhNNaXCIPN7UQzAxwOaER26gwEnFe9MkE03BVkhMq0ts63bgtgQcrhPB1YMx83gAcpkogLlDwOopARNCpO1nPsAHElfcUw9QHKseOZJe3PRC7YngXP3YgLNpsh6yPmdyFMwMoDlI2ZM1yolaaYqiZmuhb8Lb0hmtcobUj6BcwZf1deU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
