travis:
  secure:
    BINSTAR_TOKEN: VuRYVSgt1Bsgp/uw752Q7uZi4tlVc91i6QlQIiDNR03jLtgcOcGARzoknQPqRv+9ojXb+ojunW9xN59SlqrQo34eiz3ZCAz7/li5j+JYCXz/TIY89OolcnJrqUIUHnPB+JbPTkJMvlrCgQtlvof+y4j0NgaHicNcxu+9cNgdwTfGJkhRhiV7lwEX11TtEa9jscOjPFyRqBK3tjuMYEp26yAiv1iUikSY3MUbF+fmd1lRRuRW5WQ6kKEqghmgUlSJAzqRVvZYwk1YYZBIBBKnn3G2qjJ95baJWGv/IgpmqZzcxOzLW0v0chAS150KDBIgTZfdC5g1zc7QXksKwlD+LYHF52BgfP68K7ZF8EOZDZOPCECN1m3msMEEBhhKROMN9Ig/tqzHPANCiuVOkXjHTxU574h/UVS9WWuv5ByeVnotW+UsbZLnxKgeMDen80iki9K26qEA4nUWH7xiToIGPUYtwRx45fvYlIxXvQPx8NI+tx78lvB69pUqGlDDsKnVEywMOsO5v/gd6x/YKA6OJwxVx28lzgoryXCnAcp2wFb6KU0KVpmLOx36UxQcKkC+ENg/G/65DjmbRocLKdwIKdXAHpL21sdyOBaT0vd440XIQLNm54gD3mSx4sFvJ+v0Xd1uCu0g5Y7Almml2jPrOx3NNaMrj+aVmyrX9exsyjs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
