travis:
  secure:
    BINSTAR_TOKEN: VZUuDcOIIpY2rw6IsyqPgY/Abk8ahh9RpV3/tDRn26bWvL5PD2+cnZJh/NeQQ1I3wiXD0j0JtdA2k+RkyW2XhFCm6fvhXZl0XVdGvGK6FUh1uT3PG/2BoUNYJwk3cPnSEs0WPQLMz8Zk4keKpcwZqRu30m6++sVjjBnuIQK4+WEc3tSwpm1uddvbWom3tici65paklaNE6PjPatAWdhKDoUABxy3wMAsFT/urXE8q0kcsadKSHN0erJjMiI6dZaKAik83D/1WjQMYFfAViWp1U2GGessmDrhTQnWe5VtsuETQ74FitAds1xkak0z0TcP/9QCH5TZX3r3RXypbRpFjJ/szhOX538QBq9vIUHzRmUdO8EVJl6dTiCnWk03CfFR2bp6CFOVZlplHwxXK0qaa3NuPEKxn5G0c3wmXlsx4i/OIAq9077Uh7KVhElVsvzeppdL9DL3PgkHpuQ5fEfaDI9dk+kGGz7ZlSF+ncD7xqW1yWH96J6nETIZeTwa70Ki1CiFUlan0YkKA5Ljg+H6qXkR7bLJn/OC6jD3bpw6uKTB9bS9/YqPSq6BeT/QDWRYTPuBiLY4g5sWs4ZSP6C4dvJ6kXOuazLrFD7kJOYpO5LCpQkHu80xHiy3UVYP7PGPZRaXPs3aytz/A5QXAVmj2j7SW/CAvXJ+GrqeEGuP/Hk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
